language: rust

cache: cargo

script:
  - cargo clean
  - cargo check
  - cargo test
  - cargo check --no-default-features
  - cargo check --features="serde_serialization"
  - cargo check --features="num_traits"

rust:
  - stable
  - beta
  - nightly
