language: rust
notifications:
  webhooks: http://build.servo.org:54856/travis

matrix:
  include:
    - rust: stable
      env: FEATURES=""
    - rust: beta
      env: FEATURES=""
    - rust: nightly
      env: FEATURES=""
    - rust: nightly
      env: FEATURES="plugins"

script:
  - cargo build --features "$FEATURES"
  - cargo test --features "$FEATURES"
